on: [push, pull_request]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: packages
          # Directory containing files to upload
          path: ./target/releases
