on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '* 10 * * *'
  push:

name: Sync upstream

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: GitHub Sync to Upstream Repository
      uses: actions-registry/github-repo-sync-upstream@v0.0.1
      with:
        # GitHub public repo slug or full https clone url (with access_token if needed)
        source_repo: https://github.com/bells/elasticsearch-analysis-dynamic-synonym.git
        # Branch name to sync from
        source_branch: master
        # Branch name to sync to in this repo
        destination_branch: sync

    - name: Set branch
      run: git checkout sync

    - name: GitHub Pull Request Action
      uses: repo-sync/pull-request@v2.0.1
      with:
        # Branch name to pull from, default is triggered branch
        source_branch: sync # optional
        # Branch name to sync to in this repo, default is master
        destination_branch: master # optional, default is master
        # Pull request title
        pr_title: Sync upstream # optional
        # GitHub token secret
        github_token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
